apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml

namespace: gateway

images:
- name: humix-api-gateway
  newName: blgianinis/humix-api-gateway
  newTag: 7fa459e12a79382f4fa1ff3a012e0731f65cc3ff
