apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml

namespace: gateway

images:
- name: humix-api-gateway
  newName: blgianinis/humix-api-gateway
  newTag: 9a63ffd5b68ed854b3775c1ca5fe5963709d9eec
